#!/bin/bash
MENU='dmenu -l 20 -fn monospace:size=13 '
FILE="$XDG_CONFIG_HOME/dmenu-websearch/urlquery"
[ ! -f $FILE ] && exit 1

OPTIONS=( $(cat $FILE) )
OPTIONS+=("_Edit_query_file,edit")

OBJ_MENU=$(echo ${OPTIONS[@]} | tr " " "\n" | cut -d, -f1 | $MENU -i -p " WebSearch:")
[ -z "$OBJ_MENU" ] && exit 0  # exit when ESC is pressed

OBJ_SELECTED=${OBJ_MENU%% *}
OBJ_KEYWORDS=${OBJ_MENU#* }

[ -z "$OBJ_KEYWORDS" ] && exit 0 # exit when there is no keywords
OBJ_KEYWORDS=$(echo $OBJ_KEYWORDS | jq -s -R -r @uri | tr " " "+")

for i in ${OPTIONS[@]}; do
    KEYWORDS=${i%%,*}
    URLQUERY=${i##*,}

    if [ $OBJ_SELECTED = "_Edit_query_file" ]; then
        nohup st -e nvim "$FILE" > /dev/null 2>&1 &
        exit 0
    fi

    if [ $OBJ_SELECTED == $KEYWORDS ]; then
        brave_as_app.sh "${URLQUERY}${OBJ_KEYWORDS}" 2> /dev/null
    fi
done
